<Project Sdk="Microsoft.NET.Sdk">


  <ItemGroup>
    <ProjectReference Include="..\DomainCopilot.Domain\DomainCopilot.Domain.csproj" />
  </ItemGroup>

	<ItemGroup>
		<EmbeddedResource
		  Include="Documents\Answering\Prompts\GroundedAnswer.System.v1.md"
		  LogicalName="DomainCopilot.Application.Documents.Answering.Prompts.GroundedAnswer.System.v1.md" />

		<EmbeddedResource
		  Include="Documents\Answering\Prompts\GroundedAnswer.User.v1.md"
		  LogicalName="DomainCopilot.Application.Documents.Answering.Prompts.GroundedAnswer.User.v1.md" />
	</ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
